create table tab_book
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
) /

create table tab_user
(
    id       bigint generated by default as identity,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    primary key (id)
) /